#!/bin/bash 

#this script removes all docker containers

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

#remove all orphaned images:
docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
