# creating docker image for ros2
# with some basic applications


FROM gitlab-registry.tubit.tu-berlin.de/ross-lead-engineers/ross-docking-station/ros2_bouncy:clean

MAINTAINER Thomas Meschede

RUN apt update
RUN apt install -y iputils-ping openssh-server net-tools nmap vim byobu python3-numpy

RUN apt install -y ipython3 libeigen3-dev
RUN pip3 install sgp4
RUN pip3 install --upgrade pip
#TODO:
RUN pip3 install pyephem #"old" version of skyfield ()
RUN pip3 install skyfield #jplephem #maybe required if new measurements from jpl are to be used

RUN apt install -y python3-pandas python3-mysqldb
RUN apt install -y graphviz graphviz-dev doxygen doxypy inkscape doxygen-gui #doxygen-latex  this last one takes *a lot of* time 

RUN apt -y install sudo nano

#add user to docker
# create user "ross" add to sudo group and change password to "ross"
RUN useradd -ms /bin/bash ross && echo "ross:ross" | \
        chpasswd && adduser ross sudo && \
        adduser ross root

#add user to sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers        
        
#RUN chmod a+rwx /ros2_entrypoint.sh
#RUN chmod -R a+rwx /root  #is this OK, security-wise?
#RUN chown -R ross:ross /root
#RUN chmod -R a+rwx /root
#RUN chmod -R a+rwx /root/ros2-ws
#RUN sudo chmod -R a+rwx /root/ros-ws/  #is this OK, security-wise?
#CMD chown -R 1000:1000 /root/ros2-ws/

#RUN mv /root/ros2-ws /home/ross/ros2-ws && chown -R 1000:1000 /home/ross/ros2-ws

# RUN chown -R 1000:1000 /opt/ros/

#graphical environment libraries
RUN apt-get install -y pyqt5-dev python3-pyqt5


RUN apt-get install -y qt5-default libsqlite3-dev libtinyxml2-dev

#use "ross" user from here
USER ross 
#RUN echo 'echo "starting ross dev environment" \nsource /home/ross/ros2-ws/local_setup.bash' >> ~/.bashrc 
#RUN echo 'exec "$@"' >> ~/.bashrc 

#USER root -R 1000:1000 /home/ross

# RUN chmod -fR a+rwx /home/ross

#setting ros2 environment variables
#adding a script "ros2_entrypoint.sh" to the directory and as entrypoint

RUN echo '#!/bin/bash \nset -e \
    \nsource /opt/ros/$ROS_DISTRO/setup.bash \ 
    \nsource /opt/ros/$ROS_DISTRO/share/ros2cli/environment/ros2-argcomplete.bash \
    \nexec "$@"' >> /home/ross/ros2_entrypoint.sh && chmod u+rwx /home/ross/ros2_entrypoint.sh

#setting ross environment variables
#RUN echo 'echo "starting ross environment" \nsource /home/ross/install/local_setup.bash' >> ~/.bashrc     
    
    
WORKDIR /home/ross

# RUN byobu-enable

#USER root

ENTRYPOINT ["/home/ross/ros2_entrypoint.sh"]
#ENTRYPOINT ["/ros2_entrypoint.sh"]
#ENTRYPOINT /bin/bash
#ENTRYPOINT su ross -c "/bin/bash"
#CMD su ross -c "/home/ross/ros2_entrypoint.sh"
CMD ["/bin/bash"]

#http://www.yegor256.com/2014/08/29/docker-non-root.html
