FROM ubuntu:xenial
MAINTAINER Philipp Wuestenberg 

RUN locale-gen en_US.UTF-8 
ENV LANG en_US.UTF-8

RUN apt update && apt install -y curl

RUN apt update && apt install -q -y \
    git wget \
    build-essential \
    cppcheck \
    cmake \
    libopencv-dev \
    libpoco-dev \
    libpocofoundation9v5 \
    libpocofoundation9v5-dbg \
    python-empy \
    python3-dev \
    python3-empy \
    python3-nose \
    python3-pip \
    python3-setuptools \
#    python3-vcstool \
    python3-yaml \
    libtinyxml-dev \ 
    libeigen3-dev

# dependencies for testing
RUN apt-get update && apt-get install -y clang-format pydocstyle pyflakes python3-coverage python3-mock python3-pep8 uncrustify

# Install argcomplete for command-line tab completion from the ROS2 tools.
# Install from pip rather than from apt-get because of a bug in the Ubuntu 16.04 version of argcomplete:
RUN pip3 install argcomplete flake8 flake8-import-order

# dependencies for FastRTPS
RUN apt-get update && apt-get install -y libasio-dev libtinyxml2-dev

RUN curl http://repo.ros2.org/repos.key | apt-key add -

RUN sh -c 'echo "deb http://repo.ros2.org/ubuntu/main xenial main" > /etc/apt/sources.list.d/ros2-latest.list'

RUN apt update 

RUN apt install -y `apt list ros-r2b3-* 2> /dev/null | grep "/" | awk -F/ '{print $1}' | grep -v -e ros-r2b3-ros1-bridge -e ros-r2b3-turtlebot2- | tr "\n" " "`

RUN ls /opt/

#RUN source /opt/ros/r2b3/setup.bash

#RUN source /opt/ros/r2b3/share/ros2cli/environment/ros2-argcomplete.bash

RUN pip3 install -U \
    setuptools
    
RUN apt update && apt install joe

RUN echo '#!/bin/bash \nset -e \nsource /opt/ros/r2b3/setup.bash \nsource /opt/ros/r2b3/share/ros2cli/environment/ros2-argcomplete.bash \nexec "$@"' >> /ros2_entrypoint.sh && chmod 775 /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["bash"]
