FROM ubuntu:xenial
MAINTAINER Thomas Meschede

RUN apt-get clean && apt-get -y update && apt-get install -y locales

RUN locale-gen en_US.UTF-8 
ENV LANG en_US.UTF-8

RUN apt update && apt install -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    python-rosdep \
    python3-vcstool \
    wget

#\
#    python3-vcstool


# Install argcomplete for command-line tab completion from the ROS2 tools.
# Install from pip rather than from apt-get because of a bug in the Ubuntu 16.04 version of argcomplete:
RUN pip3 install \
    argcomplete\
    flake8 \ 
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-docstrings \
    flake8-import-order \
    flake8-quotes \
    pytest-repeat \
    pytest-rerunfailures \
    # From here, extra packages not available or recent enough on Xenial \
    pytest \
    pytest-cov \
    pytest-runner \
    setuptools 

RUN apt install --no-install-recommends -y \
    libasio-dev \
    libtinyxml12-dev    
    
ENV ROS_DISTRO ardent
#RUN export ROS_DISTRO=bouncy  # or ardent

COPY install_ros2_source.sh /tmp/
RUN chmod a+x /tmp/install_ros2_source.sh
RUN /tmp/install_ros2_source.sh

#RUN ls /opt/
#RUN source /opt/ros/$ROS_DISTRO/setup.bash
#RUN source /opt/ros/$ROS_DISTRO/share/ros2cli/environment/ros2-argcomplete.bash

RUN echo '#!/bin/bash \nset -e \
    \nsource /opt/ros/$ROS_DISTRO/setup.bash \
    \nsource /opt/ros/$ROS_DISTRO/share/ros2cli/environment/ros2-argcomplete.bash \
    \nexec "$@"' >> /ros2_entrypoint.sh && chmod 775 /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["bash"]
