# creating docker image for ros2
# with some basic applications


FROM gitlab-registry.tubit.tu-berlin.de/ross-lead-engineers/ross-docking-station:ros2beta1

MAINTAINER Philipp Wuestenberg version: 0.2

RUN apt update
RUN apt install -y iputils-ping openssh-server net-tools nmap vim byobu python3-numpy \
                    ipython3 libeigen3-dev
                    
RUN pip3 install --upgrade pip
RUN pip3 install sgp4 skyfield jplephem pandas 

RUN apt install -y graphviz graphviz-dev doxygen doxypy inkscape sudo nano

#add user to docker
# create user "ross" add to sudo group and change password to "ross"
RUN useradd -ms /bin/bash ross && echo "ross:ross" | \
        chpasswd && adduser ross sudo && \
        adduser ross root

#add user to sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers        
        
#RUN chmod a+rwx /ros2_entrypoint.sh
#RUN chmod -R a+rwx /root  #is this OK, security-wise?
#RUN chown -R ross:ross /root
#RUN chmod -R a+rwx /root
#RUN chmod -R a+rwx /root/ros2-ws
#RUN sudo chmod -R a+rwx /root/ros-ws/  #is this OK, security-wise?
#CMD chown -R 1000:1000 /root/ros2-ws/

RUN mv /root/ros2-ws /home/ross/ros2-ws && chown -R 1000:1000 /home/ross/ros2-ws

#graphical environment libraries
RUN apt-get install -y pyqt5-dev python3-pyqt5

#use "ross" user from here
USER ross 
#RUN echo 'echo "starting ross dev environment" \nsource /home/ross/ros2-ws/local_setup.bash' >> ~/.bashrc 
#RUN echo 'exec "$@"' >> ~/.bashrc 

#USER root

#setting ros2 environment variables
#adding a script "ros2_entrypoint.sh" to the directory and as entrypoint
RUN echo '#!/bin/bash \nset -e   \
        \nsource /home/ross/ros2-ws/local_setup.bash \
        #\nsource $PWD/install/setup.bash \
        \nexec "$@"' >> /home/ross/ros2_entrypoint.sh && chmod u+rwx /home/ross/ros2_entrypoint.sh

#setting ross environment variables
#RUN echo 'echo "starting ross environment" \nsource /home/ross/install/local_setup.bash' >> ~/.bashrc     
    
    
WORKDIR /home/ross

#USER root

ENTRYPOINT ["/home/ross/ros2_entrypoint.sh"]
#ENTRYPOINT /bin/bash
#ENTRYPOINT su ross -c "/bin/bash"
#CMD su ross -c "/home/ross/ros2_entrypoint.sh"
CMD ["/bin/bash"]

#http://www.yegor256.com/2014/08/29/docker-non-root.html
