FROM ubuntu:xenial
#FROM ubuntu:buinic
MAINTAINER Thomas Meschede

#according to this instlalation process https://github.com/ros2/ros2/wiki/Linux-Development-Setup

#RUN apt-get clean && apt-get -y update && apt-get install -y locales

#RUN locale-gen en_US.UTF-8 
#ENV LANG en_US.UTF-8

RUN apt update && apt install -y curl lsb-release
RUN curl http://repo.ros2.org/repos.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

RUN apt update && apt install -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    python-rosdep \
    python3-vcstool \
    wget

#RUN pip3 install python3-vcstool  python3-colcon-common-extensions


# Install argcomplete for command-line tab completion from the ROS2 tools.
# Install from pip rather than from apt-get because of a bug in the Ubuntu 16.04 version of argcomplete:
RUN pip3 install -U \
    argcomplete\
    flake8 \ 
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-docstrings \
    flake8-import-order \
    flake8-quotes \
    pytest-repeat \
    pytest-rerunfailures \
    # From here, extra packages not available or recent enough on Xenial \
    pytest \
    pytest-cov \
    pytest-runner \
    setuptools 

RUN apt install --no-install-recommends -y \
    libasio-dev \
    libtinyxml2-dev    

COPY install_ros2_source.sh ros2.repos /tmp/
RUN chmod a+x /tmp/install_ros2_source.sh && ./tmp/install_ros2_source.sh
    
    
#ENV ROS_DISTRO ardent

ENV ROSDIR /root/ros2_ws/

RUN echo '#!/bin/bash \nset -e \
    \nsource $ROSDIR/setup.bash \
    \nsource $ROSDIR/share/ros2cli/environment/ros2-argcomplete.bash \
    \nexec "$@"' >> /ros2_entrypoint.sh && chmod 775 /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["bash"]
