FROM gitlab-registry.tubit.tu-berlin.de/ross-lead-engineers/ross-docking-station/ros2beta3:develop

MAINTAINER Philipp Wuestenberg version: 0.1

USER root

RUN apt update 
RUN apt install -y libmysqlclient-dev libcrypto++-dev

RUN echo '#!/bin/bash \nset -e \
    \nsource /opt/ros/r2b3/setup.bash \ 
    \nsource /opt/ros/r2b3/share/ros2cli/environment/ros2-argcomplete.bash \
    \nexec "$@"' >> /home/ross/ros2_entrypoint.sh && chmod u+rwx /home/ross/ros2_entrypoint.sh

#setting ross environment variables
#RUN echo 'echo "starting ross environment" \nsource /home/ross/install/local_setup.bash' >> ~/.bashrc     

USER ross

WORKDIR /home/ross

ENTRYPOINT ["/home/ross/ros2_entrypoint.sh"]
CMD ["/bin/bash"]
