
FROM ubuntu:xenial
MAINTAINER Thomas Meschede

RUN apt-get clean && apt-get -y update && apt-get install -y locales

RUN locale-gen en_US.UTF-8 
ENV LANG en_US.UTF-8

RUN apt update && apt install -y \
    curl \
    git wget \
    build-essential \
    cppcheck \
    cmake \
    libopencv-dev \
    libpoco-dev \
    libpocofoundation9v5 \
    libpocofoundation9v5-dbg \
    python-empy \
    python3-dev \
    python3-empy \
    python3-nose \
    python3-pip \
    python3-setuptools \
    python3-yaml \
    libtinyxml-dev \ 
    libeigen3-dev \
    libasio-dev \
    libtinyxml2-dev \
    joe \
    #from this point, dependencies for testing \
    clang-format \
    pydocstyle \
    pyflakes \
    python3-coverage \
    python3-mock \
    python3-pep8 \
    uncrustify

#\
#    python3-vcstool


# Install argcomplete for command-line tab completion from the ROS2 tools.
# Install from pip rather than from apt-get because of a bug in the Ubuntu 16.04 version of argcomplete:
RUN pip3 install argcomplete flake8 flake8-import-order setuptools

ENV ROS_DISTRO ardent
#RUN export ROS_DISTRO=bouncy  # or ardent

COPY install_ros2.sh /tmp/
RUN chmod a+x /tmp/install_ros2.sh
RUN /tmp/install_ros2.sh

#RUN ls /opt/
#RUN source /opt/ros/$ROS_DISTRO/setup.bash
#RUN source /opt/ros/$ROS_DISTRO/share/ros2cli/environment/ros2-argcomplete.bash

RUN echo '#!/bin/bash \nset -e \
    \nsource /opt/ros/$ROS_DISTRO/setup.bash \
    \nsource /opt/ros/$ROS_DISTRO/share/ros2cli/environment/ros2-argcomplete.bash \
    \nexec "$@"' >> /ros2_entrypoint.sh && chmod 775 /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["bash"]
